name: Process New Issue

on:
  issues:
    types: [opened]

jobs:
  process-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get issue description
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const response = await github.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            const fs = require('fs');
            fs.writeFileSync('issue_description.txt', response.data.body);

      - name: Run Python script
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          python parse_comment.py < issue_description.txt
