name: Parse Comment

on:
  issue_comment:
    types: [created]

jobs:
  parse_comment:
    if: github.event.issue.title == 'Access Requests' && github.event_name == 'issue_comment'
    runs-on: ubuntu-latest

    steps:
      - name: Set up environment variables
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyyaml

      - name: Parse Comment
        run: python3 parse_comment.py "${{ github.event.comment.body }}"
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
