name: Parse Comment

on:
  issue_comment:
    types: [created]

jobs:
  parse_comment:
    if: github.event.issue.title == 'Access Requests' && github.event_name == 'issue_comment'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.issue.head.sha }}

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install pyyaml

      - name: Parse Comment
        run: python3 parse_comment.py "${{ github.event.comment.body }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
