name: Generate Text Output

on:
  workflow_dispatch:

jobs:
  generate_output:
    runs-on: ubuntu-latest
    steps:          
      - name: Create JSON Object
        id: create_json
        run: |
          jira_ticket="AIP-43"
          terraform_output='{
            "customer_assume_role_names": {
              "admins": {
                "AWS_Account_ID": "891377079859",
                "Principal": "arn:aws:iam::730335497822:role/aws-reserved/sso.amazonaws.com/us-east-2/AWSReservedSSO_Abbas-Admins-Dev_9fb927072f7f0f56",
                "role_name": "Opsguru-Account-Access-Admins-Dev"
              },
              "readonly": {
                "AWS_Account_ID": "891377079859",
                "Principal": "arn:aws:iam::730335497822:role/aws-reserved/sso.amazonaws.com/us-east-2/AWSReservedSSO_Abbas-Readonly-Dev_b87e2a86e56cf081",
                "role_name": "Opsguru-Account-Access-Readonly-Dev"
              }
            },
            "og_employees_aws_configs": [
              "[[profile Abbas-Admins-Dev]\nrole_arn = arn:aws:iam::891377079859:role/Opsguru-Account-Access-Admins-Dev\ncolor = 91518c\n]",
              "[[profile Abbas-Readonly-Dev]\nrole_arn = arn:aws:iam::891377079859:role/Opsguru-Account-Access-Readonly-Dev\ncolor = cc66ba\n]"
            ]
          }'
          echo "$terraform_output" > terraform_output.txt
          sed -i 's/"/\\"/g' terraform_output.txt
          
          # Convert Terraform output into JSON string
          terraform_output_json=$(echo "$terraform_output" | jq -c .)

          # Create JSON object
          json_object="{ \"jira_ticket\": \"$jira_ticket\", \"terraform_output\": \"$terraform_output_json\" }"

          # Print JSON object
          echo "$json_object" > output.json

      - name: Output Text
        run: |
          cat output.json

          
      - name: Send Output to Zapier
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" -d @output.json https://hooks.zapier.com/hooks/catch/17861705/3l8s0u7/
