name: Generate Text Output

on:
  workflow_dispatch:

jobs:
  generate_output:
    runs-on: ubuntu-latest
    steps: 
      - name: generate Terraform output
        run: |
          terraform_output_json = $(<.github/workflows/output_file.txt)
          
      - name: Create JSON Object
        id: create_json
        run: |
          jira_ticket="AIP-43"
         
          # Create JSON object
          json_object="{ \"jira_ticket\": \"$jira_ticket\", \"terraform_output\": \"$terraform_output_json\" }"

          # Print JSON object
          echo "$json_object" > output.json

      - name: Output Text
        run: |
          cat output.json

          
      - name: Send Output to Zapier
        if: always()
        run: |
          curl -X POST -H "Content-Type: application/json" -d @output.json https://hooks.zapier.com/hooks/catch/17861705/3l8s0u7/
