name: env var test

on:
  workflow_dispatch:

env:
  AWS_REGION_ENV: ${{ vars.AWS_REGION }}  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository variable
        run: |
          echo "using env: ${{ env.AWS_REGION }}"
          echo "using secrets: ${{ secrets.AWS_REGION }}"
          echo "using vars: ${{ env.AWS_REGION_ENV }}"
