name: env var test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print repository variable
        run: |
          echo "using env: ${{ env.AWS_REGION }}"
          echo "using secrets: ${{ secrets.AWS_REGION }}"
