name: CI
on:
  push:
    paths:
      - 'configurations/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD)"
          
      - name: Show changed files
        run: |
          echo "Changed file(s): ${{ steps.getfile.outputs.files }}"
