name: "Terraform Deploy"

on:
  push:
    branches:
      - main
    paths:
      - "configurations/*"

permissions:
  id-token: write # This is required for aws oidc connection
  contents: read # This is required for actions/checkout

env:
  TF_LOG: INFO
  #AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    #env:
      #TF_VAR_okta_tenant_name: ${{ secrets.OKTA_TENANT_NAME }}
      #TF_VAR_okta_api_token: ${{ secrets.OKTA_API_TOKEN }}
      #OKTA_ORG_NAME: ${{ secrets.OKTA_ORG_NAME }}
      #OKTA_API_CLIENT_ID: ${{ secrets.OKTA_API_CLIENT_ID }}
      #OKTA_API_PRIVATE_KEY: ${{ secrets.OKTA_API_PRIVATE_KEY }}
    defaults:
      run:
        shell: bash
        working-directory: .
    steps:
      - name: Git checkout
        uses: actions/checkout@v3


      - name: Extract filename
        run: |
          FILE_PATH=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep "^configurations/" | head -n 1)
          if [ -z "$FILE_PATH" ]; then
            echo "Error: No file path detected."
            exit 1
          fi
          FILE_NAME=$(basename "$FILE_PATH")
          echo "Changed file name: $FILE_NAME"
